[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "discocry"
version = "1.0"
dependencies = [
"requests", 
"torch",
"torchvision",
"torchaudio"
]

[tool.hatch.build.targets.wheel]
packages = ["discocry"]
